server:
  port: 1111
security:
  basic:
    enabled: false #开启认证
  user:
    name: admin
    password: admin
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      #defaultZone: http://user:password@localhost:${server.port}/eureka
      defaultZone: http://localhost:${server.port}/eureka
